### ISSUE TITLE
Allow alias for populate

### ISSUE THREAD

**Issue by vjpr** [Arro/airtable-json#5]
Allow specifying a name for the populated record.

```
{
  local: 'foo_linked_records',
  other: 'Foo Table',
  as: 'foos'
}
```

**Comment by Arro** [comment]
Sure, we can add this.

**Comment by Arro** [comment]
Ok, this is now implemented.  See [this](https://github.com/Arro/airtable-json/blob/main/test/populate.test.js#L79) for an example.
