### ISSUE TITLE
airtable should probably be a peer-dependency

### ISSUE THREAD

**Issue by ckeeney** [Arro/airtable-json#8]
Airtable should possible be a peer dependency instead of a dependency of this project.

Right now, the latest version of airtable is 0.11.1 and this repo is using 0.10.1 as a dependency.

Using a peer dependency instead of a dependency will let each consumer of this project manage their own version of airtable.

**Comment by Arro** [comment]
I bumped the version in `2.0.0`.  I would prefer to keep it as a dependency.  Will try to keep it updated going forward.
